#!/usr/bin/env python3
import json
from datetime import datetime, timezone
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
PUBLISHED_SETTINGS_JS = ROOT_DIR / "assets" / "js" / "studio-published-settings.js"
PUBLISHED_SETTINGS_JSON = ROOT_DIR / "assets" / "js" / "studio-published-settings.json"


class CORSRequestHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "*")
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(204)
        self.end_headers()

    def do_POST(self):
        if self.path != "/__studio/publish":
            self.send_error(404, "Not Found")
            return

        if self.client_address[0] not in {"127.0.0.1", "::1"}:
            self.send_error(403, "Forbidden")
            return

        try:
            content_length = int(self.headers.get("Content-Length", "0"))
            raw = self.rfile.read(content_length)
            payload = json.loads(raw.decode("utf-8"))
            settings = payload.get("settings")
            if not isinstance(settings, dict):
                raise ValueError("settings must be an object")

            PUBLISHED_SETTINGS_JS.parent.mkdir(parents=True, exist_ok=True)
            PUBLISHED_SETTINGS_JSON.parent.mkdir(parents=True, exist_ok=True)

            js_body = (
                "// Auto-generated by Studio local publish\n"
                f"window.__STUDIO_PUBLISHED_SETTINGS__ = {json.dumps(settings, indent=2)};\n"
            )
            PUBLISHED_SETTINGS_JS.write_text(js_body, encoding="utf-8")
            PUBLISHED_SETTINGS_JSON.write_text(json.dumps(settings, indent=2), encoding="utf-8")

            response = {
                "ok": True,
                "updatedAtUtc": datetime.now(timezone.utc).isoformat(),
                "files": [
                    str(PUBLISHED_SETTINGS_JS.relative_to(ROOT_DIR)),
                    str(PUBLISHED_SETTINGS_JSON.relative_to(ROOT_DIR))
                ]
            }

            body = json.dumps(response).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        except Exception as err:  # noqa: BLE001
            message = json.dumps({"ok": False, "error": str(err)}).encode("utf-8")
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(message)))
            self.end_headers()
            self.wfile.write(message)


def main():
    # Serve files relative to this script's folder.
    import os

    os.chdir(ROOT_DIR)
    server = ThreadingHTTPServer(("localhost", 8000), CORSRequestHandler)
    print("Serving Studio on http://localhost:8000")
    print("Local publish endpoint: POST /__studio/publish")
    server.serve_forever()


if __name__ == "__main__":
    main()
